---
root: "file:///Users/hxia/git/spring-boot-hello-ws/"
dekorateInputDir: null
dekorateOutputDir: "META-INF/dekorate"
buildInfo:
  name: "hello"
  version: "0.0.1-SNAPSHOT"
  packaging: "jar"
  buildTool: "maven"
  outputFile: "file:///Users/hxia/git/spring-boot-hello-ws/target/hello-0.0.1-SNAPSHOT.jar"
  classOutputDir: "file:///Users/hxia/git/spring-boot-hello-ws/target/classes/"
  resourceDir: "file:///Users/hxia/git/spring-boot-hello-ws/target/classes/"
scmInfo: null
